### ISSUE TITLE
Add support for custom auth providers

### ISSUE THREAD

**Issue by mithrandi** [LeastAuthority/txkube#139]
GKE uses one of these; the `users` part of the config looks like:

```yaml
users:
- name: <username>
  user:
    auth-provider:
      config:
        access-token: <cached token>
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry: 2017-06-27T16:11:31Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

Running the command given produces output like:
```json
# mithrandi@lorien ~> /usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json
{
  "configuration": {
    "active_configuration": "default",
    "properties": {
      "compute": {
        "region": "europe-west1",
        "zone": "europe-west1-d"
      },
      "core": {
        "account": "<account name>",
        "disable_usage_reporting": "True",
        "project": "<GCP project name>"
      }
    }
  },
  "credential": {
    "access_token": "<snip>",
    "token_expiry": "2017-06-27T16:11:31Z"
  },
  "sentinels": {
    "config_sentinel": "/home/mithrandi/.config/gcloud/config_sentinel"
  }
}
```

Auth works like service account auth, using the access token to do bearer token auth. What it seems you're supposed to do is use the cached token if it hasn't expired yet; or if it has expired, run the external command as given, and refresh the cached token. Fortunately `kubectl` does this, so we can implement these two parts separately.
